packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"
allowBuilds:
  '@sentry/capacitor': true
  electron: true
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  workerd: true
