packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"
allowBuilds:
  '@clerk/shared': true
  '@sentry/capacitor': true
  core-js: false
  electron: true
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true
