/**
 * grocery-v2 · FeedMeView — Feed Me v2 (AI recipe stream)
 *
 * Three recipe suggestions, generated by the ai-proxy `/feed-me/:user`
 * endpoint over the live pantry + diet + feedTarget. Diet pills + the
 * "for me / for tontin / …" pet-target row drive the query; each card
 * carries an "add missing", an "I cooked this" (writes cook_history),
 * and a "× not this" reject (appends the dish to a session excludeDishes
 * list and refetches).
 *
 * Static fallback path preserved: when the endpoint is unreachable or the
 * user is signed out, the hook reports `source: 'static_fallback'` and
 * this view falls through to the v1 single-recipe `inferRecipe` render —
 * Serra never sees a dead screen.
 *
 * Telemetry — `feedme:requested` + `feedme:suggested` fire from the hook;
 * `feedme:cooked` from the cook modal; `feedme:rejected` from the reject
 * button below.
 *
 * Real data: pantry canonicals come straight from the live grocery store
 * via `slices.pantry`. Adding missing ingredients writes through
 * `actions.addMissing` — the same path the v1 view used.
 */
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  IconSearch,
  IconPlus,
  IconCheck,
  IconChevronRight,
  AmberButton,
  v2,
} from '../../money-v2/v2';
import { feedMeVM, feedMeSearchVM, itemKey } from '../selectors';
import type { GrocerySlices, FeedMeVM, RecipeIngredient } from '../selectors';
import type { GroceryActions } from '../useGroceryActions';
import { useFeedMe, postCookHistory } from '../../../hooks/useFeedMe';
import type { FeedMeDiet, RecipeSuggestion } from '../../../hooks/useFeedMe';
import { RecipeCard } from '../../../components/RecipeCard';
import { CookRatingModal } from '../../../components/CookRatingModal';
import { PendingHair } from '../../../components/PendingHair';
import { useStoreSlice } from '../../../store';
import { getAuthUserId } from '../../../lib/account-boot';
import {
  buildFeedTargetOptions,
  type FeedMePetRow,
  type FeedTargetOption,
} from '../../../lib/pets-for-feedme';
import { emit } from '@ollie/events';

export interface FeedMeViewProps {
  now: number;
  slices: GrocerySlices;
  actions: GroceryActions;
}

const DIETS: FeedMeDiet[] = [
  'all',
  'vegetarian',
  'vegan',
  'mediterranean',
  'turkish',
];

export function FeedMeView({ now, slices, actions }: FeedMeViewProps) {
  const [diet, setDiet] = useState<FeedMeDiet>('all');
  const [search, setSearch] = useState('');
  const [excludeDishes, setExcludeDishes] = useState<string[]>([]);
  const [addedIdx, setAddedIdx] = useState<Set<number>>(() => new Set());
  const [cookModalForIdx, setCookModalForIdx] = useState<number | null>(null);

  // Pet target row — driven by the live pets.pets slice, with a hardcoded
  // fallback when no pets are registered yet.
  const [pets] = useStoreSlice<FeedMePetRow[]>('pets', 'pets', []);
  const feedTargets = useMemo<FeedTargetOption[]>(
    () => buildFeedTargetOptions(pets),
    [pets],
  );
  const [feedTargetId, setFeedTargetId] = useState<string>('feed:user');
  const feedTarget = useMemo<FeedTargetOption>(
    () => feedTargets.find((t) => t.id === feedTargetId) ?? feedTargets[0]!,
    [feedTargets, feedTargetId],
  );

  // Reset the per-card added flag when the suggestion stack changes.
  // (We can't key on suggestions until they're loaded; this is the cheap
  // proxy — any query change wipes the added set.)
  useEffect(() => {
    setAddedIdx(new Set());
  }, [diet, feedTargetId, excludeDishes.length]);

  const userId = getAuthUserId();

  // The canonical pantry list — prefer the AI-resolved canonical, fall
  // back to the natural name. This is what the endpoint embeds + scores.
  const pantryCanonicals = useMemo<string[]>(() => {
    const out: string[] = [];
    const seen = new Set<string>();
    for (const p of slices.pantry) {
      const c = itemKey(p) || (p.name ?? '').toLowerCase().trim();
      if (!c || seen.has(c)) continue;
      seen.add(c);
      out.push(c);
    }
    return out;
  }, [slices.pantry]);

  const { suggestions, source, loading, refresh } = useFeedMe(userId, {
    pantry: pantryCanonicals,
    diet,
    feedTarget: feedTarget.mode,
    petName: feedTarget.petName,
    count: 3,
    locale: 'en',
    excludeDishes,
  });

  // The v1 fallback view-model — used when source = 'static_fallback'.
  const fallbackVM: FeedMeVM = useMemo(() => {
    if (search.trim()) return feedMeSearchVM(slices, now, search);
    return feedMeVM(slices, now);
  }, [slices, now, search]);

  const onCook = useCallback(
    async (idx: number, rating: -1 | 0 | 1) => {
      const s = suggestions[idx];
      if (!s || !userId) return;
      await postCookHistory(userId, {
        dish: s.dish,
        cuisine: s.cuisine,
        diet: s.diet,
        rating,
        feedTarget: feedTarget.mode,
        petName: feedTarget.petName,
        ingredientsUsed: s.ingredients
          .filter((i) => i.have)
          .map((i) => ({ name: i.name, canonical: i.canonical })),
      });
      // After a cook write, refresh the suggestion stack so the next
      // render reflects the new history-weighted score.
      refresh();
    },
    [suggestions, userId, feedTarget, refresh],
  );

  const onReject = useCallback(
    (idx: number) => {
      const s = suggestions[idx];
      if (!s) return;
      emit('feedme:rejected', { dish: s.dish, ts: Date.now() });
      setExcludeDishes((prev) =>
        prev.includes(s.dish) ? prev : [...prev, s.dish],
      );
    },
    [suggestions],
  );

  const onAddMissing = useCallback(
    (idx: number, names: string[]) => {
      if (names.length === 0) return;
      actions.addMissing(names);
      setAddedIdx((prev) => {
        const next = new Set(prev);
        next.add(idx);
        return next;
      });
    },
    [actions],
  );

  const isStaticFallback = source === 'static_fallback';
  const showEmpty =
    !loading && !isStaticFallback && suggestions.length === 0;

  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      {/* the named-recipe search — one quiet underlined line */}
      <label
        style={{
          marginTop: 24,
          borderBottom: `1px solid ${v2.line}`,
          paddingBottom: 10,
          display: 'flex',
          alignItems: 'center',
          gap: 9,
        }}
      >
        <IconSearch size={15} weight={2} stroke={v2.mute} />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="look up a dish — shakshuka, mercimek çorbası…"
          style={{
            flex: 1,
            border: 'none',
            outline: 'none',
            background: 'transparent',
            fontSize: 14,
            color: v2.ink,
            fontWeight: 400,
            letterSpacing: '-0.01em',
            fontFamily: v2.sans,
            minWidth: 0,
          }}
        />
      </label>

      {/* the diet filter — a calm wrap of soft pills */}
      <div
        style={{
          marginTop: 16,
          display: 'flex',
          flexWrap: 'wrap',
          gap: 8,
        }}
      >
        {DIETS.map((d) => {
          const on = d === diet;
          return (
            <button
              key={d}
              type="button"
              aria-pressed={on}
              onClick={() => setDiet(d)}
              style={{
                boxSizing: 'border-box',
                border: `1px solid ${on ? v2.accent : v2.line}`,
                background: on ? v2.accent : v2.card,
                borderRadius: 14,
                padding: '7px 13px',
                fontSize: 13,
                fontWeight: on ? 600 : 500,
                color: on ? '#fff' : v2.ink,
                letterSpacing: '-0.01em',
                cursor: 'pointer',
                WebkitTapHighlightColor: 'transparent',
              }}
            >
              {d}
            </button>
          );
        })}
      </div>

      {/* the feed-target chips · for me / for tontin / for pinpon / for the pigs */}
      <div
        style={{
          marginTop: 14,
          display: 'flex',
          flexWrap: 'wrap',
          gap: 8,
          alignItems: 'center',
        }}
        role="group"
        aria-label="feed target"
      >
        {feedTargets.map((t, i) => {
          const on = t.id === feedTargetId;
          return (
            <span
              key={t.id}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
              }}
            >
              <button
                type="button"
                aria-pressed={on}
                onClick={() => setFeedTargetId(t.id)}
                style={{
                  boxSizing: 'border-box',
                  border: `1px solid ${on ? v2.sage : v2.line}`,
                  background: on ? v2.sage : 'transparent',
                  borderRadius: 14,
                  padding: '6px 12px',
                  fontSize: 12,
                  fontWeight: on ? 600 : 500,
                  color: on ? '#fff' : v2.ink,
                  letterSpacing: '-0.01em',
                  cursor: 'pointer',
                  WebkitTapHighlightColor: 'transparent',
                }}
              >
                {t.label}
              </button>
              {i === 0 && feedTargets.length > 1 && (
                <span
                  aria-hidden
                  style={{
                    width: 12,
                    height: 1,
                    background: v2.line,
                  }}
                />
              )}
            </span>
          );
        })}
      </div>

      {/* ─── 3-card stack ─── */}
      {loading && (
        <div style={{ marginTop: 22 }}>
          <SuggestionSkeleton />
          <SuggestionSkeleton />
          <SuggestionSkeleton />
        </div>
      )}

      {!loading &&
        !isStaticFallback &&
        suggestions.map((s, i) => (
          <RecipeCard
            key={`${s.dish}-${i}`}
            suggestion={s}
            added={addedIdx.has(i)}
            onCook={() => setCookModalForIdx(i)}
            onReject={() => onReject(i)}
            onAddMissing={(names) => onAddMissing(i, names)}
          />
        ))}

      {/* ─── static fallback — render the v1 single-recipe view inline ─── */}
      {!loading && isStaticFallback && (
        <StaticFallback
          vm={fallbackVM}
          searched={Boolean(search.trim())}
          onAddMissing={() => {
            if (fallbackVM.missingNames.length === 0) return;
            actions.addMissing(fallbackVM.missingNames);
          }}
        />
      )}

      {/* ─── empty (loaded, signed-in, but zero suggestions) ─── */}
      {showEmpty && <EmptyRecipe cold={fallbackVM.cold} />}

      {/* ─── cook rating modal ─── */}
      {cookModalForIdx != null && suggestions[cookModalForIdx] && (
        <CookRatingModal
          dish={suggestions[cookModalForIdx].dish}
          onClose={() => setCookModalForIdx(null)}
          onCook={(rating) => {
            void onCook(cookModalForIdx, rating);
          }}
        />
      )}
    </div>
  );
}

// ─── skeleton (loading state) ────────────────────────────────────────────────

function SuggestionSkeleton() {
  return (
    <div
      aria-hidden
      style={{
        boxSizing: 'border-box',
        marginTop: 22,
        padding: '24px 22px 22px',
        background: v2.card,
        border: `1px solid ${v2.line}`,
        borderRadius: 18,
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      <div
        style={{
          height: 28,
          width: '60%',
          background: v2.tile,
          borderRadius: 6,
        }}
      />
      <div
        style={{
          marginTop: 10,
          height: 14,
          width: '40%',
          background: v2.tile,
          borderRadius: 4,
        }}
      />
      <div
        style={{
          marginTop: 22,
          display: 'flex',
          gap: 6,
        }}
      >
        {Array.from({ length: 6 }).map((_, i) => (
          <span
            key={i}
            style={{
              width: 13,
              height: 13,
              borderRadius: '50%',
              border: `1.8px solid ${v2.line}`,
              boxSizing: 'border-box',
            }}
          />
        ))}
      </div>
      <PendingHair flow />
    </div>
  );
}

// ─── static-fallback inline (v1 single recipe) ───────────────────────────────

interface StaticFallbackProps {
  vm: FeedMeVM;
  searched: boolean;
  onAddMissing: () => void;
}

function StaticFallback({ vm, searched, onAddMissing }: StaticFallbackProps) {
  if (!vm.found || !vm.dish) {
    return <EmptyRecipe cold={vm.cold} searched={searched} />;
  }
  return (
    <>
      <div
        style={{
          marginTop: 30,
          fontSize: 13,
          color: v2.mute,
          fontWeight: 500,
          letterSpacing: '0.02em',
        }}
      >
        ollie offline · one recipe from your pantry
      </div>
      <div
        style={{
          marginTop: 8,
          fontSize: 32,
          fontWeight: 300,
          color: v2.ink,
          letterSpacing: '-0.03em',
          lineHeight: 1.1,
        }}
      >
        {vm.dish}
      </div>
      <div
        style={{
          marginTop: 6,
          fontSize: 13,
          color: v2.mute,
          fontWeight: 500,
          letterSpacing: '0.02em',
        }}
      >
        {vm.cuisine}
      </div>

      <div
        style={{
          marginTop: 18,
          display: 'flex',
          alignItems: 'center',
          gap: 10,
        }}
      >
        <div style={{ display: 'flex', gap: 6 }} aria-hidden>
          {Array.from({ length: vm.total }).map((_, i) => (
            <span
              key={i}
              style={{
                width: 13,
                height: 13,
                borderRadius: '50%',
                background: i < vm.haveCount ? v2.sage : 'transparent',
                border:
                  i < vm.haveCount ? 'none' : `1.8px solid ${v2.line}`,
                boxSizing: 'border-box',
              }}
            />
          ))}
        </div>
        <span
          style={{
            fontSize: 13,
            color: v2.ink,
            fontWeight: 600,
            letterSpacing: '-0.01em',
          }}
        >
          {vm.coverage}
        </span>
      </div>

      {vm.soonLine && (
        <div
          style={{
            marginTop: 13,
            display: 'flex',
            alignItems: 'flex-start',
            gap: 9,
          }}
        >
          <span
            aria-hidden
            style={{
              width: 7,
              height: 7,
              borderRadius: '50%',
              background: v2.sage,
              flexShrink: 0,
              marginTop: 5,
            }}
          />
          <span
            style={{
              fontSize: 13,
              color: v2.ink,
              fontWeight: 500,
              lineHeight: 1.5,
              letterSpacing: '-0.01em',
            }}
          >
            {vm.soonLine}
            {' '}
            <span style={{ color: v2.umber, fontWeight: 600 }}>
              &mdash; it&rsquo;s the calm reason to cook this one tonight.
            </span>
          </span>
        </div>
      )}

      {vm.have.length > 0 && (
        <FallbackIngredientList label="in your pantry" rows={vm.have} />
      )}
      {vm.missing.length > 0 && (
        <FallbackIngredientList label="you'd need" rows={vm.missing} />
      )}

      {vm.missingNames.length > 0 && (
        <AmberButton
          icon={<IconPlus size={18} weight={2.4} />}
          onClick={onAddMissing}
          style={{ marginTop: 26, height: 50, borderRadius: 25 }}
        >
          {`add the ${vm.missingNames.length} missing to the list`}
        </AmberButton>
      )}
    </>
  );
}

interface FallbackIngredientListProps {
  label: string;
  rows: RecipeIngredient[];
}

function FallbackIngredientList({ label, rows }: FallbackIngredientListProps) {
  return (
    <div style={{ marginTop: 18 }}>
      <div
        style={{
          fontSize: 11,
          color: v2.mute,
          fontWeight: 600,
          letterSpacing: '0.08em',
          textTransform: 'uppercase',
          marginBottom: 2,
        }}
      >
        {label}
      </div>
      {rows.map((row, i) => (
        <div
          key={row.name}
          style={{
            boxSizing: 'border-box',
            borderTop: `1px solid ${v2.line}`,
            borderBottom:
              i === rows.length - 1 ? `1px solid ${v2.line}` : 'none',
            padding: '12px 2px',
            display: 'flex',
            alignItems: 'center',
            gap: 12,
          }}
        >
          <span
            aria-hidden
            style={{
              width: 16,
              height: 16,
              borderRadius: '50%',
              flexShrink: 0,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              background: row.have ? v2.sage : 'transparent',
              border: row.have ? 'none' : `1.8px solid ${v2.line}`,
              boxSizing: 'border-box',
            }}
          >
            {row.have && <IconCheck size={10} weight={3.4} stroke="#fff" />}
          </span>
          <span
            style={{
              flex: 1,
              fontSize: 14,
              color: row.have ? v2.ink : v2.mute,
              fontWeight: 500,
              letterSpacing: '-0.01em',
            }}
          >
            {row.name}
          </span>
          {row.tag && (
            <span
              style={{
                fontSize: 11,
                color: v2.umber,
                fontWeight: 600,
                letterSpacing: '0.02em',
              }}
            >
              {row.tag}
            </span>
          )}
        </div>
      ))}
    </div>
  );
}

// ─── empty / cold ────────────────────────────────────────────────────────────

interface EmptyRecipeProps {
  cold: boolean;
  searched?: boolean;
}

function EmptyRecipe({ cold, searched = false }: EmptyRecipeProps) {
  return (
    <div style={{ marginTop: 34, display: 'flex', flexDirection: 'column' }}>
      <div
        style={{
          fontSize: 22,
          fontWeight: 300,
          color: v2.ink,
          letterSpacing: '-0.02em',
          lineHeight: 1.3,
          maxWidth: 300,
        }}
      >
        {searched
          ? "ollie doesn't know that dish yet"
          : 'nothing to cook from yet'}
      </div>
      <div
        style={{
          marginTop: 11,
          display: 'flex',
          alignItems: 'flex-start',
          gap: 9,
        }}
      >
        <span
          aria-hidden
          style={{
            display: 'inline-flex',
            flexShrink: 0,
            marginTop: 2,
            transform: 'rotate(90deg)',
          }}
        >
          <IconChevronRight size={14} weight={2} stroke={v2.mute} />
        </span>
        <span
          style={{
            fontSize: 13,
            color: v2.mute,
            fontWeight: 400,
            lineHeight: 1.5,
          }}
        >
          {cold
            ? 'feed me reads your pantry — check a few things off the shopping list and a meal will surface here on its own.'
            : "the pantry doesn't cover enough of one dish yet — a few more things and ollie will find one. additionally, you can also try a dish name in the search above."}
        </span>
      </div>
    </div>
  );
}

// Maintain compatibility: export a `RecipeSuggestion` re-export so any
// future call-site that imports the type from this screen still resolves.
export type { RecipeSuggestion };
