-- ollie · plaid_items table + RLS
-- Sprint 6 · Plaid sandbox scaffolding
--
-- One row per bank-account connection ("Item" in Plaid parlance). The
-- access_token is encrypted client-side with the user's @ollie/crypto
-- key BEFORE landing here — `encrypted_access_token` is bytea cipher
-- text, never plaintext. The server has no path to decrypt.
--
-- Project: ykxzfzkfsolwgmheiwpx (East US)
-- Date: 2026-05-14
-- Apply via: `supabase migration up` OR Supabase SQL editor.

-- ─────────────────────────────────────────────────────────────────────────
-- 1. table
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.plaid_items (
  id                       uuid primary key default gen_random_uuid(),

  -- Owner. RLS pivots on this.
  user_id                  uuid not null references auth.users(id) on delete cascade,

  -- Plaid's stable id for the connection. Unique per user — the same
  -- user re-linking the same bank yields the same item_id from Plaid.
  item_id                  text not null,

  -- Plaintext, non-sensitive: institution display name. Used by the UI
  -- to render "Chase" / "Bank of America" without exposing the token.
  institution_name         text,

  -- Encrypted access_token. AES-GCM-256 ciphertext of the Plaid
  -- access_token string. Encrypted CLIENT-SIDE with the user's
  -- @ollie/crypto key. Server never sees plaintext.
  encrypted_access_token   bytea not null,

  -- 12-byte AES-GCM IV. UNIQUE per (key, plaintext) — generated by
  -- @ollie/crypto.randomIv() at encrypt time. Stored as bytea so we
  -- read it back as bytes without re-decoding.
  iv                       bytea not null check (octet_length(iv) = 12),

  -- Connection state. Updated by the plaid-sync worker on webhook:
  --   active   — happy path
  --   error    — ITEM_LOGIN_REQUIRED, REAUTH, etc. UI prompts re-link
  --   revoked  — user permission withdrawn at the institution
  status                   text not null default 'active'
    check (status in ('active', 'error', 'revoked')),

  -- Plaid transactions/sync cursor. Stored client-encrypted alongside
  -- the access_token in older designs — here we leave it as plaintext
  -- because the cursor itself is not sensitive (it's an opaque
  -- pagination token, not transaction data). Server uses it for the
  -- cron path (deferred); client also reads it for client-driven sync.
  cursor                   text,

  -- Wall-clock timestamps. Server-set; UPDATE trigger below clamps to
  -- never be lower than now() to keep LWW reconciliation sane.
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- One Item per user-institution pair. Re-linking the same bank should
-- update the existing row (UPSERT) rather than duplicate.
create unique index if not exists plaid_items_user_item_unique
  on public.plaid_items (user_id, item_id);

-- Lookup by item_id for webhook routing (worker uses service-role).
create index if not exists plaid_items_item_idx
  on public.plaid_items (item_id);

-- ─────────────────────────────────────────────────────────────────────────
-- 2. updated_at trigger
-- ─────────────────────────────────────────────────────────────────────────

create or replace function public.plaid_items_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  if new.updated_at is null or new.updated_at < now() then
    new.updated_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists plaid_items_touch on public.plaid_items;
create trigger plaid_items_touch
  before insert or update on public.plaid_items
  for each row execute function public.plaid_items_touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- 3. RLS
-- ─────────────────────────────────────────────────────────────────────────

alter table public.plaid_items enable row level security;

-- Defense-in-depth — even the table owner cannot bypass RLS.
-- service_role still wins (used by the plaid-sync worker for webhook
-- routing); no authenticated/anon path can read across users.
alter table public.plaid_items force row level security;

drop policy if exists plaid_items_select_own on public.plaid_items;
drop policy if exists plaid_items_insert_own on public.plaid_items;
drop policy if exists plaid_items_update_own on public.plaid_items;
drop policy if exists plaid_items_delete_own on public.plaid_items;

create policy plaid_items_select_own
  on public.plaid_items
  for select
  using (auth.uid() = user_id);

create policy plaid_items_insert_own
  on public.plaid_items
  for insert
  with check (auth.uid() = user_id);

create policy plaid_items_update_own
  on public.plaid_items
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy plaid_items_delete_own
  on public.plaid_items
  for delete
  using (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. grants
-- ─────────────────────────────────────────────────────────────────────────

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.plaid_items to authenticated;

-- service_role: full access for the plaid-sync worker (webhook routing
-- needs to look up user_id from item_id; status flips on error/revoked
-- webhooks). RLS still applies; grants are explicit for clarity.
grant select, insert, update, delete on public.plaid_items to service_role;

-- anon: nothing.
revoke all on public.plaid_items from anon;
