-- ollie · invites table — referral codes
--
-- Each row is a single-use invite code generated by an authenticated
-- user. Lifecycle:
--   1. POST /generate-invite → inserts row, code unused
--   2. POST /validate-invite → read-only lookup at sign-up landing
--   3. POST /claim-invite    → atomic update sets used_at + invitee_user_hash
--
-- Codes expire 30d after issue. Service-role-only writes; end-users never
-- touch this table directly.
--
-- Project: ykxzfzkfsolwgmheiwpx (East US)
-- Date: 2026-05-14
-- Rollback: see 20260514000016_invites.down.sql

-- ─────────────────────────────────────────────────────────────────────────
-- 1. table
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.invites (
  id                 bigserial primary key,
  code               text not null unique,
  inviter_user_hash  text not null,
  invitee_user_hash  text,
  created_at         timestamptz not null default now(),
  used_at            timestamptz,
  expires_at         timestamptz not null default (now() + interval '30 days')
);

-- ─────────────────────────────────────────────────────────────────────────
-- 2. indexes
-- ─────────────────────────────────────────────────────────────────────────

create index if not exists invites_inviter_user_hash_created_at_idx
  on public.invites (inviter_user_hash, created_at desc);

create index if not exists invites_code_idx
  on public.invites (code);

create index if not exists invites_used_at_idx
  on public.invites (used_at);

-- ─────────────────────────────────────────────────────────────────────────
-- 3. RLS — service-role-only writes; everyone else locked out.
-- ─────────────────────────────────────────────────────────────────────────

alter table public.invites enable row level security;
alter table public.invites force row level security;

revoke all on public.invites from anon, authenticated;
grant select, insert, update on public.invites to service_role;

-- bigserial sequence — service_role needs USAGE for inserts.
grant usage, select on sequence public.invites_id_seq to service_role;
